---
# Our YAML file for running Travis CI.
language: python
python:
    - "3.6"

services:
    - docker
# command to install dependencies
install:
    - pip install -r scheduler/docker/requirement-dev.txt

script: 
    - coverage run scheduler/tests/test_cspsolver.py
    - coverage run scheduler/tests/test_teachercourse_csp.py
    - coverage report
