# Generated by Django 2.1.3 on 2018-11-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20181118_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateField(),
        ),
    ]
