# Generated by Django 2.1.3 on 2018-12-02 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20181202_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
