# Generated by Django 2.1.3 on 2018-12-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_delete_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('sunday', 'Sunday')], default='Monday', max_length=9),
        ),
    ]
