# Generated by Django 2.1.3 on 2018-12-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.CharField(blank=True, max_length=500, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fname',
            field=models.CharField(blank=True, max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Last Name'),
        ),
    ]
