# Generated by Django 2.1.2 on 2019-04-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_auto_20181217_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='days',
        ),
        migrations.RemoveField(
            model_name='room',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
