# Generated by Django 2.1.2 on 2019-05-01 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_auto_20190414_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('request', models.TextField()),
            ],
        ),
    ]
