# Generated by Django 2.1.2 on 2019-05-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_auto_20190501_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='dateTime',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='request',
            name='unscheduled',
            field=models.TextField(default='{}'),
        ),
    ]
