# Generated by Django 2.1.2 on 2019-05-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_auto_20190501_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_time',
            field=models.CharField(default='', max_length=128),
        ),
    ]
