# Generated by Django 2.1.2 on 2019-05-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_auto_20190502_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
