# Generated by Django 2.1.1 on 2018-10-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('building', models.CharField(blank=True, default='', max_length=128)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
