# Generated by Django 2.1.2 on 2018-10-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=128)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(max_length=128)),
                ('rtype', models.CharField(max_length=128)),
                ('length', models.IntegerField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.CharField(max_length=128)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(default='', max_length=128)),
                ('rtype', models.CharField(default='Lecture', max_length=128)),
                ('building', models.CharField(blank=True, default='', max_length=128)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=128)),
                ('room', models.CharField(max_length=128)),
                ('numStudents', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='coursecatalog',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Professor'),
        ),
    ]
