# Generated by Django 2.1.3 on 2018-11-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='rname',
        ),
    ]
