# Generated by Django 2.1.3 on 2018-11-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='numStudents',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='room',
        ),
    ]
