# Generated by Django 2.1.2 on 2018-10-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_course_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
