# Generated by Django 2.1.3 on 2018-11-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20181110_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
