# Generated by Django 2.1.2 on 2018-11-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=128)),
                ('room', models.CharField(max_length=128)),
                ('numStudents', models.IntegerField(default=0)),
            ],
        ),
    ]
