# Generated by Django 2.1.3 on 2018-11-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20181118_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course'),
        ),
    ]
