# Generated by Django 2.1.2 on 2019-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_auto_20190414_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.ManyToManyField(to='scheduler.Day'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='times',
            field=models.ManyToManyField(to='scheduler.Time'),
        ),
        migrations.AddField(
            model_name='room',
            name='days',
            field=models.ManyToManyField(to='scheduler.Day'),
        ),
        migrations.AddField(
            model_name='room',
            name='times',
            field=models.ManyToManyField(to='scheduler.Time'),
        ),
    ]
