# Generated by Django 2.1.2 on 2019-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request',
            new_name='unscheduled',
        ),
        migrations.AddField(
            model_name='request',
            name='scheduled',
            field=models.TextField(default='{}'),
        ),
    ]
