# Generated by Django 2.1.2 on 2019-05-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0028_auto_20190502_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='request',
            name='unscheduled',
        ),
    ]
